name: 05 - 2 - Event Filters and Activity Types

on: 
  pull_request:
    types: [closed]
    branches:
      - stage

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Msg
        run: |
          echo "Running whenever a PR is closed"