name: 07 - Using Expressions

on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

run-name: 07 - Expression | DEBUG - ${{ inputs.debug }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: inputs.debug == 'true'
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Printing Inpute trigger: ${{ inputs.debug }}"

