name: 07 - Using Expressions

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

run-name: 07 - Expression | DEBUG - ${{ inputs.debug }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: inputs.debug == 'true'
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Printing Inpute trigger: ${{ inputs.debug }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: "[debug] Print when triggered from develop"
        if: inputs.debug == 'true' && github.ref == 'develop'
        run: |
          echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"

