name: CI/CD Workflow

on:
  push:
    branches:
      - develop
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    env:
      CALL_BACK_API: ${{ secrets.CALL_BACK_API }}
      USRCRED: ${{ secrets.USRCRED }}
      MYENV: ${{ vars.MYENV }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: print env before setup
        run: |
          echo "Environment: ${{ github.environment }}"
          echo "Branch Name: ${{ github.ref_name }}"
          echo "Callback API Token: ${{ secrets.CALL_BACK_API }}"
          echo "User Cred: ${{ secrets.USRCRED }}"
          echo "MYENV: $MYENV"

      - name: Set up secrets and environment
        run: |
          echo "Setting up environment for branch: ${{ github.ref_name }}"
          
          # For debugging, print environment and secrets
          echo "Environment: ${{ github.environment }}"
          echo "Branch Name: ${{ github.ref_name }}"
      
      - name: Use secrets after environment setup
        run: |
          echo "Callback API Token: ${{ secrets.CALL_BACK_API }}"
          echo "User Cred: ${{ secrets.USRCRED }}"
          echo "MYENV: $MYENV"