name: CI/CD Workflow

on:
  push:
    branches:
      - develop
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      MYENV: ${{ secrets.MY_ENV }}
      REPOVAR: ${{ vars.REPOVAR }}
      USNAME: ${{ var.USERNAME }}
      USRCRED: ${{ secrets.USRCRED }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Print Before envs
        run: |
          echo "Before settings environement"
          echo "Environment: ${{ github.ref_name }}"
          echo "The secret value is: $MYENV"
          echo "The repo value is: $REPOVAR"
          echo "The username is: $USNAME"
          echo "The user credential is: $USRCRED"

      - name: Print Environment
        run: |
          echo "Environment: ${{ github.ref_name }}"

      - name: Print After envs
        run: |
          echo "After settings environement"
          echo "Environment: ${{ github.ref_name }}"
          echo "The secret value is: $MYENV"
          echo "The repo value is: $REPOVAR"
          echo "The username is: $USNAME"
          echo "The user credential is: $USRCRED"

      - name: Use Environment Secrets
        env:
          API_TOKEN: ${{ secrets.CALL_BACK_API }}
          MYENV: ${{ vars.MYENV }}
          REPOVAR: ${{ vars.REPOVAR }}
        run: |
          echo "Using API Token: $API_TOKEN"
          echo "The secret value is: $MYENV"
          echo "The repo value is: $REPOVAR"
          echo "The username is: $USNAME"
          echo "The user credential is: $USRCRED"