name: CI/CD Workflow

on:
  push:
    branches:
      - develop
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Environment
        run: |
          echo "Environment: ${{ github.ref_name }}"

      - name: Use Environment Secrets
        env:
          API_TOKEN: ${{ secrets.CALL_BACK_API }}
          MYENV: ${{ vars.MYENV }}
          REPOVAR: ${{ vars.REPOVAR }}
        run: |
          echo "Using API Token: $API_TOKEN"
          echo "The secret value is: $MYENV"
          echo "The repo value is: $REPOVAR"