name: CI/CD Workflow

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Dynamically set environment based on branch
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Environment Name
        run: |
          echo "Environment: ${{ github.ref_name }}"

      - name: Use Environment Secrets
        env:
          API_TOKEN: ${{ secrets.CALL_BACK_API }}
        run: |
          echo "Using API Token: $API_TOKEN"